version: "3.7"

services:
  chatwoot_app:
    image: chatwoot/chatwoot:latest
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      RAILS_ENV: production
      FRONTEND_URL: "https://${DOMAIN}"
      SECRET_KEY_BASE: "${SECRET_KEY}"
      SMTP_ADDRESS: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USERNAME: "${SMTP_EMAIL}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_DOMAIN: gmail.com
      MAILER_SENDER_EMAIL: "${SMTP_EMAIL}"
      POSTGRES_HOST: chatwoot_postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: chatwoot
      REDIS_URL: redis://chatwoot_redis:6379/0
      INSTALLATION_ENV: docker
    networks:
      - general_network
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chatwoot.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.chatwoot.entrypoints=websecure"
        - "traefik.http.routers.chatwoot.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"

  chatwoot_sidekiq:
    image: chatwoot/chatwoot:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: production
      FRONTEND_URL: "https://${DOMAIN}"
      SECRET_KEY_BASE: "${SECRET_KEY}"
      SMTP_ADDRESS: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_USERNAME: "${SMTP_EMAIL}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_DOMAIN: gmail.com
      MAILER_SENDER_EMAIL: "${SMTP_EMAIL}"
      POSTGRES_HOST: chatwoot_postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: chatwoot
      REDIS_URL: redis://chatwoot_redis:6379/0
      INSTALLATION_ENV: docker
    networks:
      - general_network
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers

  chatwoot_postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chatwoot
    volumes:
      - chatwoot_pgdata:/var/lib/postgresql/data
    networks:
      - general_network

  chatwoot_redis:
    image: redis:6
    volumes:
      - chatwoot_redisdata:/data
    networks:
      - general_network

networks:
  general_network:
    external: true

volumes:
  chatwoot_storage:
  chatwoot_public:
  chatwoot_mailer:
  chatwoot_mailers:
  chatwoot_pgdata:
  chatwoot_redisdata:
